---
title: "Transforming"
date: "Semester 1, 2022"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(
  comment = "#>",
  fig.path = "figures/05/", # use only for single Rmd files
  collapse = TRUE,
  echo = TRUE
)
```


> #### Associated Material
>
> Zoom notes: [Zoom Notes 05 - Transforming Data](zoom_notes_05.html)
>
> Readings:
>
> - [R for Data Science Chapter 10](https://r4ds.had.co.nz/tibbles.html)
> - [R for Data Science Chapter 11](https://r4ds.had.co.nz/data-import.html)
> - [R for Data Science Chapter 12](https://r4ds.had.co.nz/tidy-data.html)
> - [R for Data Science Chapter 13](https://r4ds.had.co.nz/relational-data.html)
> - [R for Data Science Chapter 14](https://r4ds.had.co.nz/strings.html)

\

The main purpose of module is to cover data/tidying (inside R), how to reshape data, and how to combine datasets together using a common identifier

Main topics to cover:

'tidying' data through string manipulations

- read_csv and column defs + tibbles
- unite/separate
- str_sub
- str_split
- trimws
- paste/paste0
- replace_na
- parse_numeric/as.numeric
- drop_na
- (possibly) {janitor} for clean column names
- (possibly) {broom} for turning base R stat output into nice rectangles

pivoting data long/wide -> useful for ggplot

- pivot_wider
- pivot_longer


combining datasets through joins/binds

- rbind
- cbind
- merge
- full/inner/left/right joins
- bind_rows
- bind_cols

This module is about transforming data, taking what we have and transforming in into something different. In our case, we're going to touch on three aspects - 

1. Cleaning and tidying our data using R
2. Changing the 'shape' of our data
3. Combining data together


## Cleaning and Tidying Data

Data cleaning and tidying is an integral part of data analysis and usually accounts for a significant proportion of time of the entire data -> report workflow.
In module 2 we introduced how to work with tabular data. This type of data is rectangular in nature - all rows are the same length, and all columns are the same length. Usually real life data is messy and so we have to clean and tidy it up before it is ready for use.

### Tidy Data

The three principles of tidy tabular data are:

1. Each column is a variable or property that is being measured 
2. Each row is an observation
3. A single cell should contain a single piece of information

Ideally these principles are followed from the very start when data collection is occurring

## Shaping Data




## Combining Data
