---
title: "R for Successful Student Projects"
---

\

## Is this for me?

- I want to learn about R
- I'm a student or staff member at the University of Otago

If you answered yes to both questions, this course is for you!

This course is primarily targeted to students with no or little programming experience who want to learn R for their assignments or research projects. Staff are welcome to attend too.

\

## Sign-up

<!-- Semester 1 2023 R for Successful Student Projects (R4SSP) will be online via Zoom, 10am-noon Tuesdays. An in-person help/study group session will run 3:30-4:30pm on Thursdays. -->

<!-- **Please register [using this form](https://docs.google.com/forms/d/e/1FAIpQLScVcCLMmgIYgZ2wBXgnaPL4ivhlZnhAM4jS0mHwQb6vcsJmkQ/viewform?usp=sf_link)** -->


Sign up has closed for semester 1. The course materials are free to use and work through. If you have questions or would like assistance with R, please email rtis.training@otago.ac.nz.

<!-- For more information please email rtis.training@otago.ac.nz -->

\

## Content

This course is designed to provide many avenues to learning R. We have provided both Modules that give more in-depth information on topics and handouts, which are representative of the content that will be covered in the online sessions. Both resources are designed to be complementary to each other.

We have split the content into two common purposes for learning R

- Using R for data analysis
- Programming using R

The main motivation for many people is to perform data analysis, so we have structured the order so that people can 'get stuff done' and then learn about how to improve their efficiency using R.

\

## Syllabus

Date | Week | Module | Part | Topic | Instructor
:--|:-:|:-|:-:|:--|:--:|
Week starting 6 March | 1 | Setup | | Introduce the tools: R and Rstudio | P
Week starting 13 March | 2 | Data focus | 1 | Visualising Data | M
Week starting 20 March | 3 | Data focus | 2 | Selecting and Filtering Data | P
Week starting 27 March | 4 | Data focus | 3 | Summarising Data | M
Week starting 3 April  | 5 | Data focus | 4 | Communicating Data | P
Week starting 10 April | - | MID-SEMESTER | | |
Week starting 17 April | 6 | Data focus | 5 | Tidying Data | M
Week starting 24 April | 7 |Data focus | 6 | Combining/Joining |P
Week starting 1st May | 8 | Programming focus | 1 | Functions and Choices | M
Week starting 8th May | 9 | Programming focus | 2 | Repeating code | P
Week starting 15th May | 10 | Programming focus | 3 | Workflows and debugging | M
Week starting 22nd May | --- | --- | --- | Ask us anything | P/M

Optional unit - Using version control with R (TBD)
