---
title: "Zoom Notes: Selecting and Filtering Data"
date: "Semester 1, 2022"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
library(knitr)

knitr::opts_chunk$set(
  comment = "#>",
  fig.path = "figures/", # use only for single Rmd files
  collapse = TRUE,
  echo = TRUE
)
```

> #### Associated Material
>
> Module: [Module 03 - Subsetting](03-subset.html)
>
> Reading:
>
> - [R for Data Science - Chapter 5](https://r4ds.had.co.nz/transform.html)


----


## Subsetting of vectors

- Using `[]` for extracting elements
- Subsetting by index
- Subsetting by boolean vector through conditional statements
- Use of `%in%`

### Missing Data

- Defining missing data with `NA`
- Testing for missing data with `is.na()`
- Removal of missing data
  - `[]` and `is.na()`
  - functions with an `na.rm` parameter
  
## Subsetting in 2 dimentions

- Using `[]` with 2 arguments for [rows, columns]
- Introducing `select` for columns, and `filter` for rows from `dplyr` package
  - Choosing and reordering columns with `select`
  - Use of `between` with `filter`

## Piping data between functions

- Use of the `%>%` "pipe" from the `magrittr` package

## Data manipulations

- Creating new columns
  - Using `$`
  - Using `mutate`
- Summarising data
  - `summarise` from `dplyr`
  - using `group_by` to summarise by a categorical variable
- Sorting data
  - `arrange`
  - Use of `desc` to arrange in descending order
  
## Workflows

Data subsetting and manipulations combined together with pipes to then go into ggplot.


## Exercises



