---
title: "Zoom Notes 03: Selecting and Filtering Data"
date: "Semester 2, 2023"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(palmerpenguins)

knitr::opts_chunk$set(
  comment = "#>",
  fig.path = "figures/03/", # use only for single Rmd files
  collapse = TRUE,
  echo = TRUE
)
```

> #### Associated Material
>
> Module: [Module 03 - Subsetting](03-subset.html)
>
> Reading:
>
> - [R for Data Science - Chapter 5](https://r4ds.had.co.nz/transform.html)


----


## Subsetting of vectors

- Using `[]` for extracting elements
- Subsetting by index
- Subsetting by boolean vector through conditional statements
- Use of `%in%`

### Missing Data

- Defining missing data with `NA`
- Testing for missing data with `is.na()`
- Removal of missing data
  - `[]` and `is.na()`
  - functions with an `na.rm` parameter
  
## Subsetting in 2 dimentions

- Using `[]` with 2 arguments for [rows, columns]
- Introducing `select` for columns, and `filter` for rows from `dplyr` package
  - Choosing and reordering columns with `select`
  - Use of `between` with `filter`

## Piping data between functions

- Use of the `%>%` "pipe" from the `magrittr` package

## Data manipulations

- Creating new columns
  - Using `$`
  - Using `mutate`
- Summarising data
  - `summarise` from `dplyr`
  - using `group_by` to summarise by a categorical variable
- Sorting data
  - `arrange`
  - Use of `desc` to arrange in descending order
  
## Workflows

Data subsetting and manipulations combined together with pipes to then go into ggplot.


## Exercises

1. Create the following vector and remove the missing values from it
```{r eval = FALSE}
missing_vec <- c(5, 32, NA, 94, NA, 1)
```


2. Load the Palmer Penguins dataset as below and remove all the missing values, save to a variable called *penguins_complete*.

```{r, eval=FALSE}
# if you don't have it installed
# install.packages('palmerpenguins')

library(tidyverse)
library(palmerpenguins)
penguins
```


3. How many penguins in *pengiuns_complete* have a bill_length_mm larger than 38 mm (the `n()` from `dplyr` might prove useful). Does this number change by
    a. species?
    b. island?

4. with *penguins_complete*, make a plot comparing body mass (in kg) versus flipper length for only the Chinstrap penguins. Create nice labels.
  
5. With the same data as 4), create a new column `long_flippers` that specifies TRUE/FALSE if the flipper length is longer than 200 mm, and use this column to colour your plot so that the long flipper penguins get highlighted


### Example solutions

1.

```{r zn03_soln1, class.source = "fold-hide"}
missing_vec <- c(5, 32, NA, 94, NA, 1)

missing_vec[!is.na(missing_vec)]
```

-----

2.

```{r zn03_soln2, class.source = "fold-hide"}
penguins_complete <- penguins %>% 
  filter(!is.na(bill_length_mm) | 
           !is.na(bill_depth_mm) | 
           !is.na(flipper_length_mm) |
           !is.na(body_mass_g)| 
           !is.na(sex))
```


-----

3. 

```{r zn03_soln3, class.source = "fold-hide"}
penguins_complete %>% 
  filter(bill_length_mm > 38) %>% 
  summarise(n = n())

# a)
penguins_complete %>% 
  filter(bill_length_mm > 38) %>% 
  group_by(species) %>% 
  summarise(n = n())

# b)
penguins_complete %>% 
  filter(bill_length_mm > 38) %>% 
  group_by(island) %>% 
  summarise(n = n())
```

-----

4.

```{r zn03_soln4, class.source = "fold-hide"}
penguins_complete %>% 
  mutate(body_mass_kg = body_mass_g/1000) %>% 
  filter(species == "Chinstrap") %>% 
  ggplot(mapping = aes(x = body_mass_kg, y = flipper_length_mm)) +
  geom_point() +
  labs(x = "Body Mass (Kg)",
       y = "Flipper Length (mm)",
       title = "Body Mass vs Flipper Length",
       subtitle = "in Chinstrap Penguins")
```

-----

5. 

```{r zn03_soln5, class.source = "fold-hide"}
penguins_complete %>% 
  mutate(body_mass_kg = body_mass_g/1000,
         long_flippers = flipper_length_mm > 200) %>% 
  filter(species == "Chinstrap") %>% 
  ggplot(mapping = aes(x = body_mass_kg, y = flipper_length_mm, colour = long_flippers)) +
  geom_point() +
  labs(x = "Body Mass (Kg)",
       y = "Flipper Length (mm)",
       title = "Body Mass vs Flipper Length",
       subtitle = "in Chinstrap Penguins",
       colour = "Flippers > 200 mm")

```
